CREATE TABLE T_CRB_LOCATION
(
	cLocation 		NVARCHAR(20)	NOT NULL,
	cName			NVARCHAR(100)	NOT NULL,
	PRIMARY KEY(cLocation)
)
INSERT INTO T_CRB_LOCATION VALUES('THANE', 'Thane Lodha I-Think')
INSERT INTO T_CRB_LOCATION VALUES('PBP', 'PBP Parel')
INSERT INTO T_CRB_LOCATION VALUES('MATULYA', 'Matulya Parel')
INSERT INTO T_CRB_LOCATION VALUES('OF', 'One Forbes')